version: "2"
services:
  slskd:
    image: slskd/slskd
    container_name: slskd
    ports:
      - 5030:5030
      - 5031:5031
      - 50300:50300
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
    volumes:
      - ${APP_DIR}:/app
      - ${SLSKD_CONFIG}:/config
      - ${SLSKD_DOWNLOADS_DIR}:/app/downloads
      - ${SLSKD_INCOMPLETE_DIR}:/app/incomplete
    restart: always
networks: {}
